---
- name: deleting files or directories
  hosts: all
  become: true
  gather_facts: no

  tasks:
    - name: delating a directory
      file:
        path: /home/ansadmin/opt/dir1
        state: absent
        

